language: python

python:
    - 3.7
services: 
    - mongodb

install:
  - pip install requests
  - pip install -r requirements.txt

script:
    - uwsgi --socket 0.0.0.0:5000 --protocol=http -w wsgi &
    - pytest
