---
# Documentation:
# https://help.github.com/en/articles/workflow-syntax-for-github-actions
name: Lint Code Base
on:
  push:
    branches: [main]
  pull_request:
jobs:
  build:
    name: Lint Code Base
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code base
        uses: actions/checkout@v2
      # https://github.com/github/super-linter
      - name: Lint Code Base
        uses: github/super-linter@v3
        env:
          # Should lint using black
          VALIDATE_PYTHON_PYLINT: false
          VALIDATE_PYTHON_FLAKE8: false
          VALIDATE_PHP_BUILTIN: false
          VALIDATE_PHP_PHPCS: false
          VALIDATE_PHP_PHPSTAN: false
          VALIDATE_PHP_PSALM: false
          DEFAULT_BRANCH: main
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}